vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/assets/images/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    pdf:
      uri_prefix: /pdf
      upload_destination: "%kernel.project_dir%/assets/pdf"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
